# Docker'
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:

    - task: CmdLine@2
      inputs:
        script: |
          cd $(System.DefaultWorkingDirectory)
          ls -l
          cat tsconfig.json

    - task: rapid7-insightappsec@1
      inputs:
        apiConnection: 'Sales_InsightAppSec_OrgKey'
        application: '0a22a7d1-71a1-4226-86a9-44e8926ddf5f'
        scanConfig: 'CICD'
        generateFindingsReport: true
        hasTimeout: false