# Docker'
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: rapid7-insightappsec@1
      inputs:
        apiConnection: 'IAS_Anonymoose_AzureUserKey'
        application: '07ab55b8-c94a-4ee1-8a18-860ce75b2d94'
        scanConfig: 'CICD Webscantest.com Scan'
        scanCheckInterval: '2'
        generateFindingsReport: true
        hasTimeout: true
        timeout: '45'
        hasScanGating: true
        vulnQuery: 'vulnerability.severity="HIGH"'
        publishPipelineArtifacts: true
        artifactPerReport: true
    - task: CmdLine@2
      inputs:
        script: |
          cd $(System.DefaultWorkingDirectory)
          ls -l
          cat tsconfig.json